### ISSUE TITLE
Untitled

### ISSUE THREAD

**Issue by ghost** [adelia8/x1#1]
Cool little script! Would be nice if you wouldn't be able to post comments just by entering a space (ie. by using PHP's trim function) and perhaps the possiblity to set a simple custom captcha using GD and a maximum number of characters limit. Keep up the good work.

**Comment by adelia8** [comment]
Thanks for the comment. I gotta figure out if im dumping php entirely in favor of golang or rust, not sure I want to do php any more. The secret to a.php is no closing tags on index.html - so Index.html IS the database and the php script just appends to it, and it still works. the php opens index.html, locks it, appends to it, unlocks it so its quite efficient.  Lots of others have made small php scripts here on git and other places with more functionality, this one serves as a base where one can develop from.   One can either have  the php redirect to the index.html or less work on the server, a page they click on to return to the index.html.  One can put form code on the end of a blog and its a comments system. Any css can easily be used, which makes it modular.  Oah and check out this >> https://github.com/sandlind/smolbbs there is the captcha you want :)  I know almost every small script ever made lol tell me what your are looking for exactly.  Oah and i have no idea what you are saying by " post comments just by entering a space (ie. by using PHP's trim function) " , can you pls clarify that??? Lastly, this stupid little script might be a great starting point for a good php 8.2.x app when 8.2 gets out of beta in nov :)
